# ========== Plugins ============
# TPM
set -g @plugin 'tmux-plugins/tpm'

# Save and restore tmux sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Automatic save/restore
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'


# ========== MySetup ============
# Set prefix
set -g prefix C-p
unbind C-b
bind C-p send-prefix

# Split window
unbind-key '"'
unbind-key %

bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"


# Resize panes using Shift + arrows
bind -n S-Left resize-pane -L 1
bind -n S-Right resize-pane -R 1
bind -n S-Up resize-pane -U 1
bind -n S-Down resize-pane -D 1


# Change status line background to dark blue
set -g status-style bg=default,fg=white


# Synchronize toggle
bind s set-window-option synchronize-panes \; display-message "sync toggled"
